"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import QrScanner from "./QrScanner";

type EventInfo = { id: string; name: string; venueName: string; latitude: number; longitude: number; radiusMeters: number; qrCodeValue: string };
type FormState = { firstName: string; secondName: string; regNo: string; phoneNumber: string; subCounty: string; qrCodeValue: string };
const counties = ["Bumula", "Sirisia", "Kanduyi", "Kimilili", "Mt Elgon", "Tongaren", "Webuye East", "Webuye West", "Kabuchai"];
const emptyForm: FormState = { firstName: "", secondName: "", regNo: "", phoneNumber: "", subCounty: "", qrCodeValue: "" };
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";

export default function CheckInPage() {
  const [event, setEvent] = useState<EventInfo | null>(null);
  const [form, setForm] = useState(emptyForm);
  const [position, setPosition] = useState<GeolocationCoordinates | null>(null);
  const [locationState, setLocationState] = useState("Location permission is required");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState(false);
  const [loading, setLoading] = useState(false);
  const [scannerOpen, setScannerOpen] = useState(false);

  useEffect(() => { fetch(`${apiUrl}/api/events/active`).then(async (response) => { if (!response.ok) throw new Error("No active event is available right now."); setEvent(await response.json()); }).catch((reason: Error) => setError(reason.message)); }, []);
  function distanceInMeters(latitude: number, longitude: number, targetLatitude: number, targetLongitude: number) { const earthRadius = 6371000; const radians = (value: number) => value * Math.PI / 180; const deltaLatitude = radians(targetLatitude - latitude); const deltaLongitude = radians(targetLongitude - longitude); const a = Math.sin(deltaLatitude / 2) ** 2 + Math.cos(radians(latitude)) * Math.cos(radians(targetLatitude)) * Math.sin(deltaLongitude / 2) ** 2; return earthRadius * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); }
  function locate() { if (!navigator.geolocation) { setLocationState("Location is not supported by this browser"); return; } if (!event) { setLocationState("Waiting for the active event..."); return; } setLocationState("Checking your location..."); navigator.geolocation.getCurrentPosition((result) => { const distance = distanceInMeters(result.coords.latitude, result.coords.longitude, event.latitude, event.longitude); setPosition(result.coords); setLocationState(distance <= event.radiusMeters ? "You are within the attendance zone." : `You are outside the attendance zone (${Math.round(distance)}m away).`); }, () => { setPosition(null); setLocationState("Location permission was denied"); }, { enableHighAccuracy: true, timeout: 10000 }); }
  function update(field: keyof FormState, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(eventObject: FormEvent) { eventObject.preventDefault(); setError(""); if (!event || !position) { setError("Allow location access before submitting attendance."); return; } const distance = distanceInMeters(position.latitude, position.longitude, event.latitude, event.longitude); if (distance > event.radiusMeters) { setError("Attendance not allowed at this location."); setLocationState(`You are outside the attendance zone (${Math.round(distance)}m away).`); return; } setLoading(true); try { const response = await fetch(`${apiUrl}/api/attendance`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, eventId: event.id, latitude: position.latitude, longitude: position.longitude, deviceInfo: navigator.userAgent }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Attendance could not be recorded."); setSuccess(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Attendance could not be recorded."); } finally { setLoading(false); } }

  if (success) return <main className="checkin-page"><div className="checkin-card success-state"><div className="success-mark">✓</div><p className="eyebrow">CHECK-IN COMPLETE</p><h1>Attendance Recorded Successfully.</h1><p>Thank you for participating in the KUBCSA event.</p><Link className="primary-button checkin-button" href="/">Return to dashboard</Link></div></main>;
  return <main className="checkin-page"><div className="checkin-card"><Link className="checkin-brand" href="/"><span className="brand-mark">K</span><strong>KUBCSA</strong></Link><p className="eyebrow">STUDENT ATTENDANCE</p><h1>Mark your attendance</h1><p className="checkin-intro">Verify your presence at the event venue to complete check-in.</p>{event ? <div className="active-event"><span className="live-pill"><i /> LIVE EVENT</span><strong>{event.name}</strong><span>{event.venueName}</span></div> : <div className="active-event">Loading active event...</div>}<form onSubmit={submit}><div className="form-grid"><label>First name<input required value={form.firstName} onChange={(e) => update("firstName", e.target.value)} /></label><label>Second name<input required value={form.secondName} onChange={(e) => update("secondName", e.target.value)} /></label></div><label>Registration number<input required placeholder="KSU/22/0418" value={form.regNo} onChange={(e) => update("regNo", e.target.value)} /></label><label>Phone number<input required type="tel" placeholder="07XXXXXXXX" value={form.phoneNumber} onChange={(e) => update("phoneNumber", e.target.value)} /></label><label>Sub-county<select required value={form.subCounty} onChange={(e) => update("subCounty", e.target.value)}><option value="">Select sub-county</option>{counties.map((county) => <option key={county}>{county}</option>)}</select></label><div className="location-box"><div><strong>Venue location</strong><span className={position ? "verified" : ""}>{locationState}</span></div><button type="button" className="secondary-button" onClick={locate}>Verify GPS</button></div><label>Event QR code<div className="code-input-row"><input required placeholder="Scan or enter the event QR value" value={form.qrCodeValue} onChange={(e) => update("qrCodeValue", e.target.value)} /><button type="button" className="scan-button" onClick={() => setScannerOpen(true)}>Scan</button></div></label>{error && <div className="form-error">{error}</div>}<button className="primary-button submit-checkin" disabled={loading}>{loading ? "Recording..." : "Record attendance"}</button></form><p className="privacy-note">Your registration number and phone number are used only to prevent duplicate attendance.</p></div>{scannerOpen && <div className="modal-backdrop"><QrScanner onDetected={(value) => { update("qrCodeValue", value); setScannerOpen(false); }} onClose={() => setScannerOpen(false)} /></div>}</main>;
}